version: "3"
services:
  mysql-database:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql-database
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
    restart: on-failure
  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
  kafka:
    image: "bitnami/kafka:latest"
    ports:
      - "9093:9093"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:9092,EXTERNAL://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
    depends_on:
      - zookeeper
  config:
    image: tjwjdgks43/code-etc-beta:${CONFIG_VERSION}
    container_name: config
    ports:
      - "127.0.0.1:8888:8888"
    environment:
      LOGGING_LEVEL_ROOT: ERROR
      KAFKA: http://kafka:9092
    restart: on-failure
  discovery:
    image: tjwjdgks43/code-etc-beta:${DISCOVERY_VERSION}
    container_name: discovery
    expose:
      - "8761"
    restart: on-failure
    environment:
      LOGGING_LEVEL_ROOT: ERROR
  auth-service:
    image: tjwjdgks43/code-etc-beta:${AUTH_VERSION}
    container_name: auth-service
    expose:
      - "8080"
    depends_on:
      - "discovery"
    environment:
      LOGGING_LEVEL_ROOT: ERROR
      KAFKA: http://kafka:9092
      CONFIG_SERVER: http://config:8888/
      EUREKA_SERVER: http://discovery:8761/eureka
      GATEWAY: ${GATEWAY_IP}
      WAIT_HOSTS: discovery:8761,config:8888
    restart: on-failure
  account-service:
    image: putstack/account-service:${ACCOUNT_VERSION}
    container_name: account-service
    expose:
      - "8080"
    depends_on:
      - mysql-database
    environment:
      LOGGING_LEVEL_ROOT: ERROR
      WAIT_HOSTS: discovery:8761,config:8888
      EUREKA_SERVER: http://discovery:8761/eureka
      SPRING_PROFILES_ACTIVE: stage
      CONFIG_SERVER: http://config:8888/
    restart: on-failure
  game-service:
    image: putstack/game-service:${GAME_VERSION}
    container_name: game-service
    expose:
      - "8080"
    depends_on:
      - mysql-database
      - discovery
    environment:
      LOGGING_LEVEL_ROOT: ERROR
      EUREKA_SERVER: http://discovery:8761/eureka
      SPRING_PROFILES_ACTIVE: stage
      CONFIG_SERVER: http://config:8888/
      WAIT_HOSTS: discovery:8761,config:8888
    restart: on-failure
  gateway:
    image: tjwjdgks43/code-etc-beta:${GATEWAY_VERSION}
    container_name: gateway
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - discovery
      - auth-service
      - account-service
      - game-service
    environment:
      LOGGING_LEVEL_ROOT: ERROR
      EUREKA_SERVER: http://discovery:8761/eureka
    restart: on-failure
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
          ip_range: ${IP_RANGE}
          gateway: ${GATEWAY_IP}
